name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
env:
  DEVELOPER_DIR: /Applications/Xcode.app
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build iOS
        run: xcodebuild -scheme SwiftyCreatives build -destination "generic/platform=iOS"
      - name: Build macOS
        run: xcodebuild -scheme SwiftyCreatives build -destination "generic/platform=macOS"
  test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test macOS
        run: xcodebuild -scheme SwiftyCreatives test -destination "generic/platform=macOS"
