name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
env:
  DEVELOPER_DIR: /Applications/Xcode_15.2.app
jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - name: Build macOS
        run: set -o pipefail && xcodebuild -scheme SwiftyCreatives build -destination "generic/platform=macOS" | xcpretty
      - name: Build iOS
        run: set -o pipefail && xcodebuild -scheme SwiftyCreatives build -destination "generic/platform=iOS" | xcpretty
      - name: Build visionOS
        run: set -o pipefail && xcodebuild -scheme SwiftyCreatives build -destination "generic/platform=visionOS" | xcpretty
  test:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - name: Test macOS
        run: set -o pipefail && xcodebuild -scheme SwiftyCreatives test -destination "platform=macOS,arch=arm64" | xcpretty
      - name: Test iOS
        run: set -o pipefail && xcodebuild -scheme SwiftyCreatives test -destination "name=iPhone 14 Pro" | xcpretty
  build-examples:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - name: Build macOS Example
        run: cd Examples/ExampleMacOSApp && set -o pipefail && xcodebuild -scheme ExampleMacOSApp build -destination "generic/platform=macOS" | xcpretty
      - name: Build iOS Example
        run: cd Examples/ExampleiOSApp && set -o pipefail && xcodebuild -scheme ExampleiOSApp build -destination "name=iPhone 14 Pro" | xcpretty
      - name: Build visionOS Example
        run: cd Examples/ExampleVisionOS && set -o pipefail && xcodebuild -scheme ExampleVisionOS build -destination "generic/platform=visionOS" | xcpretty
